CREATE DATABASE AppNodejs;
--USERS TABLE
USE Nodejs;
CREATE TABLE users(
    id INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(16) NOT NULL,
    password VARCHAR(100) NOT NULL,
    fullname VARCHAR(100),
    PRIMARY KEY(id)
);
ALTER TABLE users MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--IMG TABLBE
CREATE TABLE img(
    id int(11) NOT NULL,
    title VARCHAR(20) NOT NULL,
    img MEDIUMBLOB NOT NULL,
    description TEXT,
    user_id INT(11),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, --CUANDO SE CREO EL REGISTRO
    CONSTRAINT fk_users FOREIGN KEY(user_id) REFERENCES users(id) --LLAVE FORANEA ON REFERENCIA DESDE LA TABLA USERS EN EL CAMPO ID
    --EL CAMPO user_id ESTA RELACIONADO CON LA TABLE users EL CAMPO id
);
ALTER TABLE img ADD PRIMARY KEY(id);
ALTER TABLE img MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;